# Generated by Django 5.2.11 on 2026-02-11 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rationale', models.TextField(blank=True)),
                ('change_type', models.CharField(choices=[('sop', 'Lab SOP change'), ('calibration', 'Equipment calibration change'), ('software', 'Software change'), ('med_device_doc', 'Medical device document change')], default='sop', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
