# Generated by Django 5.2.11 on 2026-02-11 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.changerequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
